nephio-project/porch

Makefile
test/e2e/cli/cli_test.go
test/e2e/cli/cluster.go
test/e2e/cli/config.go
test/e2e/cli/testdata/git-server.yaml
test/e2e/cli/testdata/repo-register/config.yaml
test/e2e/cli/testdata/rpkg-clone/config.yaml
test/e2e/cli/testdata/rpkg-copy/config.yaml
test/e2e/cli/testdata/rpkg-get/config.yaml
test/e2e/cli/testdata/rpkg-init-deploy/config.yaml
test/e2e/cli/testdata/rpkg-init/config.yaml
test/e2e/cli/testdata/rpkg-lifecycle/config.yaml
test/e2e/cli/testdata/rpkg-push/config.yaml
test/e2e/cli/testdata/rpkg-update/config.yaml
test/e2e/suite.go

This adds the CLI E2E tests. A couple notes:
- Like the other e2e tests, in order to run you need to create a cluster and deploy porch, and set E2E=1
- These require that porchctl is built and in the path.
- Currently they also require that kpt is built and in the path, because a few tests execute `kpt fn`. There is no need to have a version of kpt with `kpt alpha` commands, just `kpt fn`.
I manually ran the e2e tests in this PR.

Add CLI e2e tests

---

.github/workflows/porch-e2e.yaml

Verify if prow tide merge flow is blocked by an edit to an existing github workflow.

Test github workflow update against prow

---

pkg/cli/commands/rpkg/del/command_test.go
pkg/cli/commands/rpkg/propose/command_test.go
pkg/cli/commands/rpkg/proposedelete/command_test.go
pkg/cli/commands/rpkg/push/command_test.go
pkg/cli/commands/rpkg/push/testdata/test-fjdos9u2nfe2f32/.KptRevisionMetadata
pkg/cli/commands/rpkg/push/testdata/test-fjdos9u2nfe2f32/deployment.yaml

This change introduces unit tests to some of the rpkg commands.

Add unit tests for rpkg commands

---

pkg/cli/commands/rpkg/push/command.go

**What type of PR is this?**
> Uncomment only one  /kind <> line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>  /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
**What this PR does / why we need it:**
See https://github.com/nephio-project/nephio/issues/471
The push fails due to the hidden .KptRevisionMetadata file being missing, the reason is that the "porchctl rpkg pull" command must be used to pull down the package to the local file system prior to pushing local contents.
porchctl -n porch-demo rpkg init zooby --repository=management --workspace=v1                                   
porchctl rpkg push management-f329f708454bb52906e17266ac6cf689c325f6fa -n porch-demo aaa/bbb
Error: …

Improve error message emitted when metadata is missing

---

docs/tutorials/porch-development-environment/bin/replace-gitea-service-ports.yaml
docs/tutorials/porch-development-environment/bin/setup.sh

Includes the following changes:
- remove edge1 cluster
- ensure that Gitea's nodePort matches with the port that is forwarded to the host in the kind cluster's config
- the following values are turned into parameters: 
- name of kind cluster, 
- name of git repo, 
- Gitea external IP
- script made idempotent (you can rerun it without any cleanup)
- script exits on error
- Gitea install package is manipulated by KRM functions instead of sed
- check if git user.name config is set
- bugfix: wait for Deployment availability instead of Pod readiness

Refactor of the Developer Environment setup script

---

.github/workflows/porch-e2e.yaml
.github/workflows/porchctl-cli-e2e.yaml
.github/workflows/release.yaml
api/go.mod
build/Dockerfile
build/Dockerfile.apiserver
build/Dockerfile.etcd
controllers/Dockerfile
controllers/go.mod
controllers/packagevariantsets/pkg/controllers/packagevariantset/render.go
default-go-lint.mk
default-go-test.mk
default-gosec.mk
examples/apps/hello-server/Dockerfile
examples/apps/hello-server/go.mod
go.mod
test/Dockerfile

**What type of PR is this?**
> Uncomment only one  /kind <> line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>  /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake
**What this PR does / why we need it:**
- Updated go version in go.mod files
- Updated go version in github workflows
- Updated base image to 1.22.2-bookworm in Dockerfiles
- Updated Go/Golang-CI/GoSec versions in makefiles
**Which issue(s) this PR fixes:**
Fixes [Issue 510](https://github.com/nephio-project/nephio/issues/510).
**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?:**
no

Upgrade Porch to Go 1.22

---

docs/tutorials/porch-development-environment/README.md

We don't need to have a workload cluster in the development tutorial. If users want to create a workload cluster for their development task, they can follow the "Starting with Porch" tutorial.

Remove references to the 'edge1' cluster from the porch developer tutorial

---

default-go-test.mk

Update the gotests image in the makefile to be compatible with the latest go version.

Update gotests in makefile to latest version

---

docs/09-function-runner-pod-templates.md
func/internal/podevaluator.go
func/internal/podevaluator_podmanager_test.go
func/server/server.go
pkg/util/util.go

Intended to fix https://github.com/nephio-project/nephio/issues/571 See documentation inlined.

Pod templating for function runner 

---

release/tag/goreleaser.yaml

This change injects the release version into the run.go module during build time using goreleaser. 
This updates the version from "unknown" to the current version set by goreleaser.

#735 - Fix porchctl version by injecting release version into run.go module

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/registry/porch/background.go
pkg/registry/porch/packagecommon.go
scripts/create-deployment-blueprint.sh
test/e2e/e2e_test.go

Fixes https://github.com/nephio-project/nephio/issues/725
This is a quick-fix for the bug, but has suboptimal performance. 
Solving the problem in a performant way would require a much deeper redesign of the code. The Porch re-architecture process is on-going, and the proper solution is expected to stem from it.

Fix caching in case multiple Repository resources point to the same git repo

---

.github/workflows/porch-e2e.yaml
.github/workflows/porchctl-cli-e2e.yaml

There's no need to run E2E tests when Prow configuration files change. Also they have their own checks defined in test-infra's Prow configuration.

Excluding changes in Prow files from triggering e2e runs

---

.prow.yaml
.vscode/launch.json
Makefile

This PR contains:
* FIX for a prow issue introduced by #72 
* new make target called `destroy` that deletes the current porch deployment
* better strategy to keep (kpt) state between porch deployments (instead of trying to preserve the `resourcegroup.yaml` file)
* use server-side apply for porch deployments
* do not build container images of locally running processes
* fix function-runner IP address in `.vscode/launch.json`
WARNING: unfortunately the new porch deploy method conflicts with the old one, so you have to delete and recreate your kind cluster after this change is merged into your local setup.

Yet another improvement to development process

---

test/e2e/cli/cli_test.go

When running the Porch end to end tests on ARM architecture, kpt issues the warning below when it's images don't match the host machine's architecture:
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`
However, regardless of the warning above, the kpt command does work.
Currently, the test code checks if there is anything on stderr in the test and fails if there is. This PR adds code that if the only output on standard output is the warning message above, then the warning is ignored. If there is anything else on the standard error, then the test will fail.

Ignore ARM architecture warning on e2e test results

---

pkg/git/package.go
test/e2e/cli/testdata/rpkg-clone/config.yaml
test/e2e/cli/testdata/rpkg-copy/config.yaml
test/e2e/cli/testdata/rpkg-init-deploy/config.yaml
test/e2e/cli/testdata/rpkg-init/config.yaml
test/e2e/cli/testdata/rpkg-push/config.yaml
test/e2e/e2e_test.go

The .metadata.uid field of PackageRevisions are  simply created from  the name and revision of the package. It is not unique in the whole cluster, because it doesn't contain the name of the registry or the namespace.
Fixes https://github.com/nephio-project/nephio/issues/748
Based on #57

Make PackageRevision's metadata.uid field unique

---

.github/workflows/porchctl-dev-release.yaml

This workflow will build porchctl binary from 'main' branch with just 'make porchctl' each successful merge. This binary whill then be used for e2e tests running 'main'.
Workflow will create release called 'Porchctl build from main' and replace it each build so it's always latest.

Porchctl dev release workflow

---

controllers/packagevariants/pkg/controllers/packagevariant/packagevariant_controller.go

This improves the response times of recoverable PackageVariant errors, e.g. normal errors related to optimistic locking when updating PackageRevisionResources objects.
This should improve, but not solve https://github.com/nephio-project/nephio/issues/770 and https://github.com/nephio-project/nephio/issues/462 .

PackageVariant controller: Use the default exponential back-off in case of errors, instead of a constant 30 sec retry

---

.github/workflows/porchctl-dev-release.yaml

This PR fixes the `porchctl` command so that it runs on Ubuntu 20.04. The `porchctl` command must be built on the same or an earlier Ubuntu version as the e2e tests or it won't run in the e2e tests and will break the tests.

Fix the porchctl build to run on Ubuntu 20.04

---

.vscode/launch.json
Makefile

This PR tweaks the launch configuration and Makefile to allow remote debugging of Porch on a Nephio sandbox VM.
This tweak requires explicit inventory parameters to be used, see https://github.com/nephio-project/test-infra/pull/293
The documentation for remote VM debugging is in this PR:  https://github.com/nephio-project/docs/pull/158

Sandbox debugging

---

api/porchconfig/v1alpha1/config.porch.kpt.dev_repositories.yaml
api/porchconfig/v1alpha1/types.go
pkg/git/git.go

Set the default value for the "main" branch in the OpenAPI schema part of the Repository CRD, and reject empty values for this field.
This PR doesn't really change the behavior of Repository: the branch field remains optional, and the default value of "main" will be applied if omitted. 
The two differences that the PR introduces are:
- the value "main" will be visible in the Repository object when queried (e.g. by the Get/List operation), even if it wasn't set explicitly upon creation
- setting the branch name explicitly to the empty string is not allowed anymore, and will cause the object creation to be rejected
The last point in more detail:
- omitting the `spec.git.branch` field is accepted and assigns the default value ("main") to the branch field:
- this is accepted and assigns the …

Make the default value of Repository's spec.git.branch field explicit

---

pkg/cli/commands/rpkg/push/command.go

we are compiling the porchctl to use it on Windows. the proposed fix is changing the Windows path representation to the Unix-based one.

fix porchсtl push method for windows

---

build/Dockerfile
build/Dockerfile.apiserver
build/Dockerfile.etcd
controllers/Dockerfile
examples/apps/hello-server/Dockerfile
func/Dockerfile
func/Dockerfile-wrapperserver
test/Dockerfile

New versions of docker reports warnings like the following while building our Dockerfiles:
`=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 15)`
This trivial PR fixes those.

Fix minor warnings in Dockerfiles

---

.github/workflows/porch-e2e.yaml
.github/workflows/porchctl-cli-e2e.yaml
.github/workflows/porchctl-dev-release.yaml

Update dev build gh acrion to only trigger when merged to main.
Fix e2e gh actions to trigger when deployments dir is changed

Fix dev release

---

deployments/porch/5-rbac.yaml
pkg/apiserver/webhooks.go
pkg/util/util.go
test/e2e/suite.go

Remove hardwired string literals as the default values of WEBHOOK_SERVICE_NAME and WEBHOOK_SERVICE_NAMESPACE environment variables.
This PR introduces the following changes in behavior:
The value of WEBHOOK_SERVICE_NAME is determined by one of the followings (in precedence order):
- the WEBHOOK_SERVICE_NAME environment variable
- the name of the service specified in the `APIService` object named `v1alpha1.porch.kpt.dev`
The value of WEBHOOK_SERVICE_NAMESPACE is determined by one of the followings (in precedence order):
- the WEBHOOK_SERVICE_NAMESPACE environment variable
- the CERT_NAMESPACE environment variable (deprecated, please don't use this!!!)
- the namespace of the service specified in the `APIService` object named `v1alpha1.porch.kpt.dev`
- namespace of the current process (if …

More sensible defaults for webhook environment variables

---

internal/kpt/util/porch/approval.go
pkg/cli/commands/rpkg/approve/command.go
pkg/cli/commands/rpkg/propose/command.go
pkg/cli/commands/rpkg/propose/command_test.go
pkg/cli/commands/rpkg/proposedelete/command.go
pkg/cli/commands/rpkg/proposedelete/command_test.go
pkg/cli/commands/rpkg/reject/command.go
pkg/cli/commands/rpkg/reject/command_test.go
pkg/cli/commands/rpkg/update/command.go
scripts/cleanup-after-tests.sh
test/e2e/cli/testdata/rpkg-lifecycle/config.yaml

We are using the Update API operation in the porchctl CLI commands for multiple purposes. Those can fail due to normal optimistic locking behavior if another process tries to manipulate the same object (typically PackageRevision) in parallel. In a reconciliation loop these naturally occurring errors correctly cause a retry, but in the CLI these errors cause the command to fail. 
This PR adds a retry loop around those Update calls, thus implementing default optimistic locking behavior.
This should fix some flaky errors that we experienced in our Nephio end-to-end tests, e.g.: https://github.com/nephio-project/nephio/issues/803. 
NOTE: using server-side apply instead of Update doesn't work when we try to change the lifecycle state of PackageRevisions, because of at least these two reasons: …

 Retry 'Update' operations that are failing due to normal optimistic locking behavior in CLI commands

---

.github/workflows/release.yaml

It will only trigger on tag named in scheme vX.Y.Z

change trigger for porchctl release build

---

.github/workflows/release.yaml

This will exclude -pre tags from triggers in release GitHub Actions

GitHub Actions exclude -pre tags

---

pkg/cache/cache.go

There is no need for the `else` block here because the if `err` is nil, it always returns in the `if` block.

Remove confusing else statement in cache.go

---

.vscode/launch.json
pkg/cache/repository.go
pkg/meta/store.go
pkg/registry/porch/packagecommon.go
pkg/registry/porch/packagerevision.go
pkg/registry/porch/packagerevisionresources.go
test/e2e/e2e_test.go
test/e2e/suite.go
test/e2e/suite_utils.go

Implements [#657](https://github.com/nephio-project/nephio/issues/657)
Add mutexes to the following operations to resolve session conflicts:
- `Create()`, `Update()`, and `Delete()` in pkg/registry/porch/packagerevision.go
- `Update()` in pkg/registry/porch/packagerevisionresources.go
- `Update()` in pkg/registry/porch/packagerevisions_approval.go
This restricts concurrent incoming requests to operate one at a time on a given package revision; requests received while one of the above operations is in progress will immediately return a 409 Conflict error response.
For example, given a request X which attempts to `Update()` package revision P, while another request Y is already in progress to `Delete()` P, request X will return a 409 Conflict response.

Add session-conflict resolution for concurrent CUD operations on package revisions

---

pkg/git/git.go
pkg/git/package.go
pkg/repository/repository.go
test/e2e/e2e_test.go
test/e2e/suite_utils.go

Fixes [#814](https://github.com/nephio-project/nephio/issues/814)
- make revision incrementation on rpkg approve work with --directory repos
- add new Directory attribute to PackageRevisionKey
- and use it when matching PackageRevisions to filter out from the List operation
- package approval flow looks for previous copies of the package to determine new latest revision string (e.g. v1 -> v2)
- this involves matching the package-for-approval's path attribute against existing packages' packageName attribute
- however:
- when a repo is registered using --directory to associate it with a subfolder in the upstream Git repo, packageName is deliberately trimmed of the directory attribute if it exists
- but the path in the package-for-approval still has the directory part
- so no existing …

Fix revision incrementation when approving a package in a repo registered with --directory

---

pkg/engine/engine.go
test/e2e/e2e_test.go

When changes are pushed to a package that are identical to the existing package, the `updatedResources` method returns the resources. However the 'if' block that starts at line 1053 does not set `applied` to the value of the resources, so when the loop terminates after the `continue` statement, the function returns with `applied` having a value of an empty string map. This value is set in the draft package revision, resulting in all the existing resources in the package draft being erased.

Fix overwrite of package resources with empty resource map

---

pkg/engine/clone.go
pkg/engine/clone_test.go
pkg/engine/engine.go
pkg/engine/mergekey.go
pkg/engine/patchgen.go
pkg/engine/update.go

- Use "_" instead of names for unused function parameters
- Use "_" instead of names for unused variables
- Remove unused functions and variables
- Replace `fmt.Errorf` with `errors.New` when error message contains no formatting

Implement improvements identified by static linting

---

pkg/engine/clone_test.go
pkg/engine/engine.go
pkg/engine/update.go

The `loadResourcesFromDirectory` and `writeResourcesToDirectory` functions are declared in `engine.go` but are only used in `update.go`. This PR moves those functions to the file `update.go` for readability.

Move functions

---

.vscode/launch.json
pkg/cache/memory/repository.go

This PR fixes two code warnings in repository.go:
- A double import
- An unnecessary guard around a delete in a slice

Fix two warnings in repository.go

---

Makefile
cmd/porchctl/run/run.go
deployments/porch/3-porch-server.yaml
pkg/apiserver/apiserver.go
pkg/cmd/server/start.go
pkg/cmd/server/start_test.go
pkg/registry/porch/background.go

This change makes the background job periodic polling interval configurable and matches with the repo sync interval. 
This change makes the default repo sync and periodic sync intervals 10 minutes by default.
This change also hides the request-timeout parameter from the porchctl command. This is done because currently in Kubernetes source code, client context is cancelled at exactly 34 seconds - https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/rest.go#L53.

Fix hardcoded background job periodic poll interval

---

.github/workflows/release.yaml
release/tag/goreleaser.yaml

When publishing a new GitHub release generate a porch blueprint kpt package with `make deployment-config`, and add the results to the release assets

Add a porch blueprint (kpt package) to GitHub Release assets

---

.vscode/launch.json
Makefile
deployments/porch/2-function-runner.yaml
deployments/porch/3-porch-server.yaml
func/internal/executableevaluator.go
func/internal/podevaluator.go
func/internal/podevaluator_podmanager_test.go
func/server/server.go
func/wrapper-server/main.go
pkg/apiserver/apiserver.go
pkg/cmd/server/start.go
pkg/engine/clone_test.go
pkg/engine/grpcruntime.go
pkg/engine/options.go
test/e2e/e2e_test.go

Fixes https://github.com/nephio-project/nephio/issues/823
PR #121 successfully solved the issue of creating/updating/querying big packages via the porch API. However if a big package has a non-empty pipeline, the rendering of those large packages fail with an error message mentioning grpc max message size (see the issue referenced above). This PR fixes that.
(It also contains some minor refactoring that eliminates some unnecessarily long argument lists in function-runner.)

Fix rendering big (>4MB) packages with function-runner

---

.github/workflows/release.yaml

Unfortunately my previous PR #133 broke the release script, since it relied on the kpt CLI that is missing from the runner.
This PR hopefully fixes that.

Fix "release" GitHub Action

---

scripts/run-load-test.sh

This PR adds a script to run a load test on Porch.
The PR on the docs repo that documents the script is here: https://github.com/nephio-project/docs/pull/185

Script to run a Porch load test

---

pkg/cache/memory/draft.go
pkg/cache/memory/repository.go
pkg/git/draft.go
pkg/git/git.go
pkg/oci/mutate.go
pkg/repository/fake/repository.go
pkg/repository/repository.go
pkg/task/generictaskhandler.go
pkg/task/taskhandler.go

This is a cleanup PR that renames the interface `PackageDraft` to `PackageRevisionDraft`. This interface is used to manage package revision drafts. The interface is renamed to improve the readability of the Porch code.

Rename interface PackageDraft to PackageRevisionDraft

---

pkg/engine/engine.go
pkg/registry/porch/packagerevisionresources.go
pkg/task/generictaskhandler.go
test/e2e/cli/config.go
test/e2e/cli/suite.go
test/e2e/cli/testdata/rpkg-push/config.yaml

Tackles [#818](https://github.com/nephio-project/nephio/issues/818) and potentially [#658](https://github.com/nephio-project/nephio/issues/658).
The main change this PR proposes is that a package who's render pipeline has failed during a [porchctl rpkg push] should not be allowed to go further into git. 
There are fundamental issues with the package in this scenario and can lead to more issues down the line for example in #818. 
They should be handled by the user on the local version and retry should be attempted until the package's kpt function pipeline succeeds.

Render pipeline failure should block package push to remote

---

pkg/cache/cache.go
pkg/cache/memory/cache.go
pkg/cache/memory/cache_test.go
pkg/registry/porch/background.go

This PR adds passing of the context on the `cache.CloseRepository()` interface function signature and adds tracing to the cache `CloseRepository()` function.

Add tracing to cache close function

---

test/ociserver/pkg/oci/registry.go

The time handling on the ListTags function in the OCI registry code is not portable, it only works on Linux machines. The updated code below is portable.

Make time handling in OCI platform independent

---

pkg/task/clone.go
pkg/task/eval.go
pkg/task/generictaskhandler.go
pkg/task/replace_test.go
pkg/task/replaceresources.go
pkg/task/update.go

Refactoring to make the task code easier to follow:
1. Add `mutation` interface test to all mutation structs
2. Rename `mutationReplaceResources` to `replaceResourcesMutation` to make the struct naming consistent with the other mutation structs
3. Move the `updatePackageMutation` from "generaictaskhandler.go" to a new go file "update.go" so that all mutations are in their own source file
4. Move the `mutationReplaceResources` from "generaictaskhandler.go" to a new go file "replaceresources.go" so that all mutations are in their own source file

Refactor task package to make mutations more visible

---

pkg/task/generictaskhandler.go
test/e2e/cli/config.go
test/e2e/cli/suite.go
test/e2e/cli/testdata/rpkg-push/config.yaml

This PR tackles 2 small bugs.
The first was mistakenly introduced in [#145](https://github.com/nephio-project/porch/pull/145).
The bug causes the error message of porchctl cmd's that edit the package-revision's resources AND they fail e.g. copy failing due to not being published, will also be padded with the error message related to rendering error.
Example error with bug
```
porchctl -n porch-demo rpkg copy porch-test-3a6d81f91097fa9b935edd53e4f20110785cc25a --workspace=asdsqweaasdads 
Error: Internal error occurred: source revision must be published
Error occurred rendering package in kpt function pipeline.
Package has NOT been pushed to remote.
Please fix package locally (modify until 'kpt fn render' succeeds) and retry.
```
Error should be as follows
```
porchctl -n porch-demo rpkg …
```

Fix misleading error msg & adding Stderr "contains" argument check in CLI tests

---

.vscode/launch.json

This is a quick and simple PR for adding a sample configuration in the launch.json for running porchctl commands such that you can use the debugger on the command operation outside the porch server itself.

Adding launch.json porchctl cmd debugger

---

pkg/cache/memory/cache_test.go
pkg/cache/memory/repository.go
pkg/engine/engine.go
pkg/git/package.go
pkg/meta/fake/memorystore.go
pkg/meta/store.go
pkg/oci/oci.go
pkg/repository/fake/packagerevision.go
pkg/repository/repository.go

This PR is the first step in allowing a different implementation of the metadata store.
By using the generic K8S metadata struct, we are not dependent on a struct defined in the meta package and can use a different implementation in the future.

Use Kubernetes metadata struct rather than Porch derived metadata struct

---

.gitignore
internal/kpt/fnruntime/container.go
internal/kpt/fnruntime/runner.go
internal/kpt/fnruntime/runner_test.go
internal/kpt/util/get/get.go
pkg/apiserver/apiserver.go
pkg/cmd/server/start.go
pkg/kpt/fs_test.go
pkg/kpt/render_test.go
pkg/task/render_test.go

The default-image-prefix server argument was not passed along to the KRM function runner previously. This PR is a fix for that.

Pass default-image-prefix to function runners

---

pkg/apiserver/webhooks_test.go

This PR attempts to break up the TestWatchCertificates test into each individual test case with more time allowance for each test alongside a slightly better approach.
This does not fix the fundamental issue of the testing using logs but it should hopefully lead to far less flakiness in this test

Reformatting TestWatchCertificates

---

controllers/packagevariants/pkg/controllers/packagevariant/injection.go
controllers/packagevariants/pkg/controllers/packagevariant/packagevariant_controller.go

Current code in package variant controller was assuming that "status.upstreamLock.Git.Ref" in PackageRevision resource will always having proper value. But status.upstreamLock field in PackageRevision could be nil in initial transition stage. Due to which Porch was crashing. Issue is fixed as part of this PR

fix for sporadic porch crash during new package revision

---

pkg/git/git.go

The git repo code holds a cache of the package revisions that are in state "proposed-delete". Entries in this cache were not removed when the package revision was actually deleted. This bug was not noticed before because the periodic job fixed up the proposed-delete cache and it ran every minute. Now that the periodic job is running every 10 minutes, this bug became more obvious.
Before:
```
% porchctl -n porch-demo rpkg init network-function --repository=porch-test --workspace=myws
porch-test-ed65de69336c5d0d329867dd874a568460ffda0b created
% porchctl -n porch-demo rpkg propose porch-test-ed65de69336c5d0d329867dd874a568460ffda0b
porch-test-ed65de69336c5d0d329867dd874a568460ffda0b proposed
% porchctl -n porch-demo rpkg approve porch-test-ed65de69336c5d0d329867dd874a568460ffda0b …
```

Propose delete cache updated when package revision is deleted

---

.github/workflows/gosec-scan.yaml
.gitignore
default-gosec.mk

Adding a gh action to run gosec scans on PRs. Non blocking presubmit job will be enabled once all issues are resolved.
Update the existing gosec make target "make gosec" to align with the gh action verison

Add gosec gh action

---

pkg/cache/memory/cache.go

I see there was a typo error at line number 174 in file path pkg/cache/memory/cache.go
It should be CloseRepository instead of OpenRepository.

Fixing typo in path pkg/cache/memory/cache.go at line 174

---

pkg/apiserver/apiserver.go
pkg/cache/memory/cache.go
pkg/cmd/server/start.go
pkg/git/git.go

This is the first in a series of PRs to rationalize the option passing in Porch, ultimately to make it easier to implement alternative cache implementations and also to allow repository systems as well as git to be used.
In this PR, the `use-git-cabundle` option and the `UseGitCaBundle` variables are renamed to remove references to GIT because a user defined CA bundle could be used for systems other than Git.

Rename GitCaBundle to UserDefinedCaBundle

---

.github/workflows/porchctl-dev-release.yaml

A tag named "main" (same as the branch name "main") in the GitHub repo confuses git clients and scripts executing git operations, so we should avoid it if possible.
This 3 character long PR tries to fix the GH action that regularly recreates that tag,

Prevent creating "main" tag and release on Github

---

.prow.yaml
build/Dockerfile
build/Dockerfile.apiserver
build/Dockerfile.etcd
controllers/Dockerfile
default-go-lint.mk
default-go-test.mk
examples/apps/hello-server/Dockerfile
func/Dockerfile
func/Dockerfile-wrapperserver
go.mod
scripts/boilerplate.go.txt
scripts/boilerplate.yaml.txt
scripts/setup-dev-env.sh
test/Dockerfile

Update Docker files to target version.
Update make targets with new go version.
Fix header templates.

Bump go versions to 1.23.5

---

pkg/cache/memory/repository.go

As of now normal mutex is used in cache repository which will make multiple read to wait for mutex. Changed mutex in cache repository to read write mutex so that all concurrent reads are allowed.
Also. Added missing mutex unlock in case of failure

changed mutex in cache repository to read write mutex so that all concurrent reads are allowed

---

pkg/engine/engine.go
pkg/repository/util.go

Related issue: [#835](https://github.com/nephio-project/nephio/issues/835)
This change is meant more as a mitigation than a solution to the problem, returning a more clear error message for a PackageRevision create/update failure when blockOwnerDeletion is enabled.

Add additional info to error when blockOwnerDeletion is enabled

---

test/e2e/e2e_test.go

This PR adds an e2e test to verify the Repository Modify operation functionality. The test ensures that:
1. Repository modifications are processed correctly
2. Modified repositories maintain proper Ready state
3. Repository conditions are updated appropriately after modification
The test follows existing e2e test patterns and verifies:
- Repository can be modified successfully
- Description updates are persisted
- Repository Ready condition remains True after modification
- Proper cleanup is performed after test completion
Related PR: #167 (Repository Modify event implementation)
Testing:
- Added new e2e test: TestRepositoryModify
- Ran e2e tests locally
- Follows existing test patterns in the codebase

adding e2e test validation for PR #167 Modify event on the porch Repo Custom Resource

---

.vscode/settings.json
sonar-project.properties

Adding a sonar.properties file.
This setup was tested locally and verified that it covers and excludes the relevant areas.
The vscode settings entry was added when I boud my ide sonarlint to the sonarqube project. Users will have to genertse their own token to do the same.

Add sonar props file

---

.sonarcloud.properties

Based on the documentation 
https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/automatic-analysis/#deactivating-automatic-analysis
> You can refine the configuration of your analyses by adding a .sonarcloud.properties file to your repository’s default branch. Note that this is different from the sonar-project.properties file used for CI-based analysis.
And a test on a private fork (on the graph started with these properties and then without, the duplications and issues increase)
I based it on this app https://github.com/marketplace/sonarcloud
[My previous PR](https://github.com/nephio-project/porch/pull/195) was based on a local instance of SonarCloud
Change-Id: I9b904a192f4b51d51066151aa552277ac3782090

Add properties file for automatic analysis

---

scripts/cleanup-after-tests.sh
scripts/generate-api.sh
scripts/run-load-test.sh

This PR added missing copyrights to files in the Porch codebase.
https://github.com/nephio-project/porch/pull/189
However, in scripts, the shebang #! must be on the first line.
This PR fixes the scripts and moves the shebang to the first line of the file.

Move shebang before copyright notices in scripts

---

.github/workflows/sonar-ci-artifacts.yaml
.github/workflows/sonarcloud.yml

Github secrets are not passed to workflows triggered by PRs coming from forks.
This PR is adding a prestep workflow to produce and archive the coverage report and it's related PR number.
Then the sonar gh action retrieves this data and pushes the report to soanrqube.

Add workflow to archive coverage data

---

scripts/remove-porch-server-from-deployment-config.sh

This script is called when using: `make run-in-kind` or `make run-in-kind-no-server`
Adding an extra check with OR to see if the user is using Windows with WSL and Docker Desktop where the DOCKER_HOST env should be unset.
This way porch packagerevisions will be available, and the setup will be successful.
Change-Id: Ie1f275b75e435cb5926efdc3ade52453e39b3b6c

Adding check for docker desktop

---

.github/workflows/golangci-lint.yaml
default-go-lint.mk
test/e2e/e2e_test.go
test/e2e/suite.go
test/e2e/suite_logs.go
test/e2e/suite_utils.go
test/e2e/update_test.go
test/ociserver/pkg/oci/responses.go

The main E2E test suite was a wrapper around `testing.T` and mostly mimicking testify's functionality. In this PR I "ported" the suite over to testify, making it more IDE friendly in my experience.
I also removed a lot of redundant context passing, pushing it down to the helper functions instead. Furthermore, I fixed the lint issues in the tests and removed the exclusion in the github action.

Port main E2E test suite to testify

---

sonar-project.properties
test/performance/README.md
test/performance/gitea-secret.yaml
test/performance/logger.go
test/performance/metrics.go
test/performance/porch_metrics_test.go
test/performance/prometheus_metrics.go
test/performance/promql_queries.txt
test/performance/types.go

**Proposal: Porch Performance Testing Framework with Prometheus Integration**
**Overview**
This proposal introduces a comprehensive performance testing framework for Porch, designed to measure and monitor repository and package management operations using Prometheus. The framework provides automated setup, detailed metrics collection, and extensive reporting capabilities.
Basic Test Execution
```
go test -v ./... \
--repos=2 \
--packages=5 \
--packageRevisions=4
```
**Goals**
1. Establish automated performance testing for Porch operations
2. Implement comprehensive metrics collection using Prometheus
3. Provide detailed operation monitoring and reporting
4. Enable configurable test scenarios
**Implementation Details**
1. Framework Components
- Automated Setup
- Prometheus Configuration
- …

Proposal- Porch Performance Testing Framework - Operation Flow with Prometheus

---

pkg/cli/commands/rpkg/update/command.go
test/e2e/cli/testdata/rpkg-update/config.yaml

https://github.com/nephio-project/nephio/issues/898
The line
```go
Upstream: cloneTask.Clone.Upstream,
```
could potentially cause issues if the `cloneTask.Clone.Upstream` object is modified elsewhere in the code. Since Go passes structs by value, this line assigns a reference to the `Upstream` field of the `cloneTask.Clone` object. If the `Upstream` field is later modified, it could unintentionally affect the `cloneTask.Clone.Upstream` object.
Making a copy ensures that the `Upstream` object in the new task is independent of the original `cloneTask.Clone.Upstream`.
```go
Upstream: *cloneTask.Clone.Upstream.DeepCopy(),
```
---
Here's an example based on the script from before:
1. **Deployment v1** was cloned from **Blueprint v1**.
2. **Blueprint v2** was copied and approved.
3. …

porchctl - Fix Update issue when the package has local changes

---

test/e2e/performance/config.yml
test/e2e/performance/performance_suite.go
test/e2e/performance/prometheus_in_docker.sh
test/e2e/performance/rules.yml

with net/http Server with address ":2113" serves the metrics using ipv6, adding an ip would serve on ipv4 "127.0.0.1:2113"
```bash
#Before
$ netstat -tuln | grep 2113
tcp6       0      0 :::2113                 :::*                    LISTEN
#After
$ netstat -tuln | grep 2113
tcp        0      0 127.0.0.1:2113          0.0.0.0:*               LISTEN
```
This is beneficial for developers on WSL2 that does not support ipv6 connections to the docker host.
Added also `rules.yml` with basic warnings and alerts http://localhost:9090/rules

Update performance test Prometheus config

---

func/internal/podevaluator.go
func/server/server.go

Avoid the default list of fn pods starting up at deploy time which can be expensive on a limited internet connection.

Add flag to disable fn pods deployed at startup

---

pkg/task/generictaskhandler.go
pkg/task/generictaskhandler_test.go
pkg/task/patchgen.go
pkg/task/patchgen_test.go

https://github.com/nephio-project/nephio/issues/898
The following error still occurs in some corner cases when updating a package using the `copy-merge` strategy:
```
Error: Internal error occurred: error applying patch: conflict: fragment line does not match src line
```
To address this issue, this solution avoids performing a `git diff` between the original and local files for update strategies such as `copy-merge` and `force-delete-replace`.
* Added a function to check whether the update strategy is `copy-merge` or `force-delete-replace`.
* For files that have changed, the patching step is skipped. Instead, the original content is returned, and the loop continues to process the remaining files.
* After all tasks are completed, the update function will overwrite any changed files. As a …

Skip patch mutation for Copy-Merge

---

pkg/cache/crcache/repository.go

Porch polls repositories twice when it sets up the sync job on a repository. This change eliminates the duplicate poll.

Fix double polling of repositories at sync startup

---

controllers/packagevariantsets/pkg/controllers/packagevariantset/packagevariantset_controller.go
controllers/packagevariantsets/pkg/controllers/packagevariantset/packagevariantset_controller_test.go
controllers/packagevariantsets/pkg/controllers/packagevariantset/validate.go
controllers/packagevariantsets/pkg/controllers/packagevariantset/validate_test.go

This PR fixes references of upstream PRs by allowing support for workspace names on PVS upstream specifications in the same way as it is already allowed on PV specifications.
This change is required to fix the end to end tests in test-infra.

Update PVS to allow WorkspaceName on Upstream PR references

---

internal/kpt/util/update/copy-merge.go
internal/kpt/util/update/copy-merge_test.go

Issue Explained here: https://github.com/nephio-project/nephio/issues/913
1. Clone blueprint -> deployment
2. update deployment to a newer version of blueprint
3. metadata.name in the Kptfile changes from deployment to blueprint (because the whole file gets overridden)
Before:
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata: # kpt-merge: /blueprint
name: blueprint
upstream: ..
upstreamLock: ..  
```
After this change:
```
apiVersion: kpt.dev/v1
kind: Kptfile
metadata: # kpt-merge: /deployment
name: deployment
upstream: ..
upstreamLock: ..  
```
The metadata name of the package `deployment` that was cloned from `blueprint` will not change, but the upstream and upstreamLock will update to the new version of the blueprint like in the past
steps taken:
- Removed the walk over each file in …

Update Kpt File before replacing the files for `copy-merge`

---

func/healthchecker/healthchecker.go
internal/kpt/fnruntime/runner.go

In this PR the function runner logging is improved as follows:
- Increase the klog log-level(3) for health checks. This makes sure that at the default log-level(2), the health check messages are not printed every 10 seconds. 
- It removes printing an empty line and it appends the resouceCount number to the same line during rendering.

Improve function runner logging

---

pkg/cli/commands/rpkg/docs/docs.go
pkg/cli/commands/rpkg/push/command.go
test/e2e/cli/testdata/rpkg-push/config.yaml

This PR resolves an issue where rpkg push would wait forever if the dirname/stdin were not provided as a parameter to the cli command. 
Here, the PR aligns rpkg push with how stdin is used in kubectl apply. 
The command will only wait for stdin if '-' is added to the cli command after the package name.

Align rpkg push with kubectl

---

pkg/registry/porch/packagecommon.go
pkg/registry/porch/packagecommon_test.go

This PR fixes  https://github.com/nephio-project/nephio/issues/921
This fix ensures that the watch functionality for PackageRevisions respects the namespace scoping. Previously, even when a specific namespace was provided with the -n flag, events from other namespaces were incorrectly included in the output stream. This update filters the watch stream properly, showing only events from the requested namespace, improving clarity and expected behavior for users.

Fix watch namespace filter 

---

func/internal/podevaluator.go
func/internal/podevaluator_podmanager_test.go
test/e2e/e2e_test.go

In the current implementation, function pods that enter a `Failed` state are not evicted from the cache. Consequently, Porch continues to reuse these failed pods for subsequent evaluations, leading to persistent failures even after the underlying issue (e.g., registry unavailability) has been resolved.
This PR introduces the following changes:
* Detects and deletes `Failed` pods during evaluation request handling.
* Deletes and evicts `Failed` pods during garbage collection.
* Adds asynchronous pod deletion (`deleteFailedPod`) with cache safety checks.
* Ensures fresh pod creation is triggered immediately after eviction.
* Adds a unit test case under `TestPodManager` to validate `Failed` pod handling.

Evict failed pods from cache and trigger fresh pod creation.

---

func/internal/podevaluator.go

This PR fixes an intermittent 'connection refused' error when the function runner attempts to create a grpc connection with the KPT pods.

add WaitForReady in grpc client creation

---

pkg/cache/dbcache/dbpackagerevision.go
pkg/cache/dbcache/dbpackagerevision_test.go

When cloning, if the upstream package is still in draft, we cannot use a real Git upstream reference (the PR is not in Git yet), we have to send back the upstream reference as it would be if the package was in a Git repository.

Fix upstream references in DB Cache

---

pkg/externalrepo/git/package_tree.go
pkg/repository/repository.go

This PR addresses and fixes https://github.com/nephio-project/nephio/issues/950.
There was seemingly an unnecessary trim which when the packageName contained the value of the directory variable in the yaml file of a repository resource would be trimmed away from the package.

Fixing repo directory value trimming when pkg name contains it

---

func/internal/podevaluator.go

This PR fixes https://github.com/nephio-project/nephio/issues/952
The getFuncEvalPodClient was always called, which internally caused errors while creating pods and services because of duplication. 
This change runs the getFuncEvalPodClient only if the image is not in the map.

Fix an issue where multiple Kpt pods were getting created

---

internal/kpt/util/render/executor.go
internal/kpt/util/render/executor_test.go
pkg/kpt/api/kptfile/v1/types.go

Suppose we have a kpt package with a root directory and multiple sub-directories in the following folder tree structure:
The current hydrate function will operate bottom-up because it's using recursion. So the order in the example will be:
C, A, B, ROOT -> [Depth-First Post-Order](https://miro.medium.com/v2/resize:fit:640/format:webp/1*4KpXD6en9pbN2mgbq4XraA.gif)
> **_NOTE:_**  In the code the subpackages are ordered from left to right in ascendant alphabetical order.
I am proposing a top-to-bottom approach to add beside the hydrate function, using 2 arrays as queues so that the order in the example will be:
ROOT, A, B, C -> [Breadth-First Level-Order](https://i.giphy.com/media/LP0RRlb0SXqw6GqcyK/giphy.gif)
`hydrateTopToBottom` operates only if an annotation `kpt.dev/bfs-rendering: …

Top To Bottom Render order

---

func/internal/podevaluator.go

This PR fixes an issue where executing concurrent API calls without KPT pods/services active was leading to svc already exists. 
Instead of crashing the whole flow, this change will try to retrieve the service if it already exists.

Fix "svc already exists" errors while executing concurrent API calls

---

pkg/util/merge3/merge3_test.go
pkg/util/merge3/merge3_util_test.go
pkg/util/merge3/testdata/infer-crd-empty-dest/destination.yaml
pkg/util/merge3/testdata/infer-crd-empty-dest/original.yaml
pkg/util/merge3/testdata/infer-crd-empty-dest/updated.yaml
pkg/util/merge3/testdata/infer-crd-empty-orig/destination.yaml
pkg/util/merge3/testdata/infer-crd-empty-orig/original.yaml
pkg/util/merge3/testdata/infer-crd-empty-orig/updated.yaml
pkg/util/merge3/testdata/infer-crd-empty-updated/destination.yaml
pkg/util/merge3/testdata/infer-crd-empty-updated/original.yaml
pkg/util/merge3/testdata/infer-crd-empty-updated/updated.yaml
pkg/util/merge3/testdata/one-key-crd-empty-dest/destination.yaml
pkg/util/merge3/testdata/one-key-crd-empty-dest/fruitstore.crd.yaml
pkg/util/merge3/testdata/one-key-crd-empty-dest/original.yaml
pkg/util/merge3/testdata/one-key-crd-empty-dest/updated.yaml
pkg/util/merge3/testdata/one-key-crd-empty-orig/destination.yaml
pkg/util/merge3/testdata/one-key-crd-empty-orig/fruitstore.crd.yaml
pkg/util/merge3/testdata/one-key-crd-empty-orig/original.yaml
pkg/util/merge3/testdata/one-key-crd-empty-orig/updated.yaml
pkg/util/merge3/testdata/one-key-crd-empty-updated/destination.yaml
pkg/util/merge3/testdata/one-key-crd-empty-updated/fruitstore.crd.yaml
pkg/util/merge3/testdata/one-key-crd-empty-updated/original.yaml
pkg/util/merge3/testdata/one-key-crd-empty-updated/updated.yaml
pkg/util/merge3/tuple.go

@lapentad found that having `InferAssociativeLists` enabled for the 3 way merge causes errors for empty lists. In my opinion this is a bug in kyaml.
In this PR I added a lot more tests for this behaviour, including some for infer which are skipped for now. Also had to skip `one-key-crd-empty-dest` because somehow during the merge of the associative list in the test, one of the list items does not get it's `tag` field set, resulting in our KubeObject/SubObject util code returning in error:
```
err: node was not a string, was
```
Problematic example:
```
Tag = ""
Value = "apple"
```
The other element right after:
```
Tag = "!!str"
Value = "pear"
```
This also might be a bug in kyaml, but should be investigated further.

Disable InferAssociativeLists, add more tests

---

pkg/apiserver/apiserver.go
pkg/externalrepo/git/git.go
pkg/externalrepo/types/externalrepotypes.go

It looks like #192 seems to have broken custom git CA bundle resolution, and this PR is meant to fix that by separating the git auth and the git CA bundle secret resolvers.

Fix custom CA bundle resolution

---

pkg/cli/commands/rpkg/docs/docs.go
pkg/cli/commands/rpkg/upgrade/command.go
pkg/cli/commands/rpkg/upgrade/command_test.go

Adding a "strategy " flag to the upgrade command
`porchctl rpkg upgrade repository.package.1 --revision=2 --workspace=2 --strategy=copy-merge`
If you do not specify `--strategy` it will use `resource-merge`

Manually choose the upgrade strategy in porchctl

---

internal/kpt/util/pkgutil/pkgutil.go
internal/kpt/util/pkgutil/pkgutil_test.go
internal/kpt/util/update/copy-merge.go
internal/kpt/util/update/copy-merge_test.go

Following this behaviour:
origin = blueprint1
update = blueprint2
local  = deployment2 (copy of deployment1)
1. Replace files in local with updated if they are the same
2. Delete files in local only if they were in origin but not in update
3. Keep intact any files in local that were not in origin or update
Legend
- ✅ = File exists
- ❌ = File missing
Origin | Update | Local (before) | Result in Local (after) | Reason
-- | -- | -- | -- | --
✅ | ✅ | ✅ | ✅ (from Update) | File replaced by update version
✅ | ✅ | ❌ | ✅ (from Update) | File restored by update
✅ | ❌ | ✅ | ❌ (deleted) | File removed in update (stale)
✅ | ❌ | ❌ | ❌ | Already gone
❌ | ✅ | ✅ | ✅ (from Update) | File overwritten by update
❌ | ✅ | ❌ | ✅ (from Update) | File added by update
❌ | ❌ | ✅ | ✅ (unchanged) | Local-only file …

Added RemoveStaleItems in `copy-merge`

---

func/wrapper-server/main.go
internal/kpt/util/render/executor.go
pkg/engine/pushpr.go

This PR resolves https://github.com/nephio-project/nephio/issues/962.
It adds a fix to the missing tasks list in certain situations with db-cache.
This PR updates the wrapper-server log to remove a new line with empty stderr for every kpt execution. 
This PR removes an empty line printed in the porch-server logs after pipeline execution.

Fix missing Tasks List in db-cache, update wrapper-server and render logs

---

pkg/cli/commands/rpkg/upgrade/command.go
pkg/cli/commands/rpkg/upgrade/command_test.go

Explained here
https://github.com/nephio-project/nephio/issues/970
Added:
- `findUpstreamByLock` if the `findEditOrigin` fails (returns empty string)
- the function will find the "best" candidate to be the upstream based on the `status.UpstreamLock.Git.Ref`
Question:
-  Could there be multiple package revisions that match the same upstream repository and directory but have different revisions or refs?

Porchctl: Upgrade fallback when there is no original edit task

---

deployments/local/postgres/postgres-statefulset.yaml

Bitnami are shifting to a new image registry model which entails cutting off several Docker images they provide. Postgres (used in Porch for deploying the DB cache in local/development environments) is still available, but requires changing the image tag in the StatefulSet manifest. Without this, the end-to-end test runs using the DB Cache will fail, with the porch-server microservice getting stuck in a crash loop, unable to connect to Postgres, until the run times out and is auto-cancelled after 6 hours.

Postgres image update to new Bitnami repository

---

pkg/cache/dbcache/dbcache_test.go
pkg/cache/dbcache/dbpackagerevision_test.go
pkg/cache/dbcache/dbpackagerevisionsql_test.go
pkg/cache/dbcache/dbpackagesql_test.go
pkg/cache/dbcache/dbrepository_test.go
pkg/cache/dbcache/dbrepositorysql_test.go
pkg/cache/dbcache/dbreposync_test.go
pkg/cache/dbcache/dbsql_test.go
pkg/cache/dbcache/util_test.go

Rewrote the DB cache tests to use testify rest suite, and to also be skipped if the user is root, because postgres complains in that case. I think this is an improvement to these tests overall.
Reasoning: Had some trouble running the all unit tests on a container that uses the root user, and skipping the DB cache tests seemed problematic the way they were using TestMain.

Rewrite DB cache tests to use testify test suite

---

.github/workflows/porchctl-dev-release.yaml
.github/workflows/release.yaml

Fix release GH actions failing to find missing go.mod
---
- What changed:  Move code checkout before setup-go action
- Why it’s needed:  setup-go fails to find go.mod
- How it works:  
---
- Closes/Fixes #  
---
---
---
1.  
2.  
3.  
---
- Known issues:  
- Further improvements:  
- Review notes:

Fix porch release gh actions
