- pkg/cache/cache.go
- pkg/registry/porch/background.go
Fixes https://github.com/nephio-project/nephio/issues/451
> Fix problem with git subdir repos

- Makefile
Add kind cluster context input
Add kubeconfig input
> Add kind and k8s input to run_in_kind target

- Makefile
- docs/running-porch-in-kind-cluster.md
- scripts/create-deployment-kpt.sh
- scripts/install-local-kpt-pkg.sh
- test/pkgs/gitea-dev/Kptfile
- test/pkgs/gitea-dev/README.md
- test/pkgs/gitea-dev/deployment.yaml
- test/pkgs/gitea-dev/gitea-config.yaml
- test/pkgs/gitea-dev/gitea-init.yaml
- test/pkgs/gitea-dev/http-svc.yaml
- test/pkgs/gitea-dev/namespace.yaml
- test/pkgs/gitea-dev/secret-git-user.yaml
- test/pkgs/gitea-dev/ssh-svc.yaml
Enhancements to the orig run-in-kind make target to use the catalog porch kpt pkg.
Add an optional minimal in memory gitea kpt pkg.
Add make target  deploy-gitea-dev-pkg to deploy a local kpt pkg for testing purposes.
Add a readme guide to enable the basic setup.
> Add run-in-kind-kpt setup and readme

- docs/tutorials/starting-with-porch/README.md
- docs/tutorials/starting-with-porch/blueprints/.gitignore
- docs/tutorials/starting-with-porch/blueprints/network-function-auto-namespace/Kptfile
- docs/tutorials/starting-with-porch/blueprints/network-function-auto-namespace/README.md
- docs/tutorials/starting-with-porch/blueprints/network-function-auto-namespace/deployment.yaml
- docs/tutorials/starting-with-porch/blueprints/network-function-auto-namespace/package-context.yaml
- docs/tutorials/starting-with-porch/blueprints/network-function/Kptfile
- docs/tutorials/starting-with-porch/blueprints/network-function/README.md
- docs/tutorials/starting-with-porch/blueprints/network-function/deployment.yaml
- docs/tutorials/starting-with-porch/kind_edge1_cluster.yaml
- docs/tutorials/starting-with-porch/kind_management_cluster.yaml
- docs/tutorials/starting-with-porch/kpt_packages/.gitignore
- docs/tutorials/starting-with-porch/metallb-conf.yaml
- docs/tutorials/starting-with-porch/name-namespace-variant.yaml
- docs/tutorials/starting-with-porch/porch-repositories.yaml
- docs/tutorials/starting-with-porch/repos/.gitignore
- docs/tutorials/starting-with-porch/simple-variant.yaml
- docs/tutorials/starting-with-porch/tmp_pacakges_for_deployment/.gitignore
Tutorial to get users started on Porch
> Added porch tutorial

- docs/porchctl-cli-guide.md
Update guide for release artefact
> Update porchctl cli guide

- docs/tutorials/porch-development-environment/README.md
> Add warning about using WSL2 and fix lint errors

- .prow.yaml
Porch images will be built every merged PR and pushed to Docker Hub with tags: 'latest' and usual tag that's prow's job ID
> Adding porch image builds for every PR merged tagged latest

- .github/workflows/porch-e2e.yaml
- .github/workflows/porchctl-cli-e2e.yaml
- Makefile
- deployments/porch/1-namespace.yaml
- deployments/porch/2-function-runner.yaml
- deployments/porch/3-porch-server.yaml
- deployments/porch/4-apiservice.yaml
- deployments/porch/5-rbac.yaml
- deployments/porch/6-rbac-bind.yaml
- deployments/porch/7-auth-reader.yaml
- deployments/porch/8-auth-delegator.yaml
- deployments/porch/9-controllers.yaml
- docs/running-porch-in-kind-cluster.md
- docs/tutorials/porch-development-environment/bin/setup.sh
- go.mod
- scripts/clean-kind-only-e2e-test.sh
- scripts/create-deployment-blueprint.sh
Build local porch pkg for test runs.
Remove GCP specific make targets etc.
> Use local porch pkg build for e2e tests

- .github/workflows/porchctl-dev-release.yaml
Adding tar/gz step to have uniform artifact format.
> Adding tgz creation step

- pkg/registry/porch/fieldselector.go
- pkg/repository/repository.go
- test/e2e/e2e_test.go
Fixes https://github.com/nephio-project/nephio/issues/724
> Add support for new field selectors: spec.workspaceName and spec.lifecycle

- pkg/cli/commands/rpkg/push/command.go
`PackageRevisionResources`' spec.Resources field is defined as a map of strings. This means that Update calls to `PackageRevisionResources` objects will convert all file contents to valid UTF-8 text during JSON serialization. This is achieved by changing invalid bytes to the Unicode replacement character, that corrupts the contents of binary files.
This is the root cause of https://github.com/nephio-project/nephio/issues/778.
This PR fixes https://github.com/nephio-project/nephio/issues/778 by adding a clear error message regarding the lack of support of binary files. 
The alternative solution would be to change the porch API in a non-backward compatible way (e.g. encode all file contents in base64, etc.), however that should be part of the ongoing porch re-architecture process.
> Return an error if 'porchctl rpkg push' detects a binary file in the kpt package

- build/Dockerfile
Rebuild the porch docker images
> Test build images prow rerun

- .prow.yaml
This seems to cause problems with recent changes
> disable caching for dev images build

- scripts/run-load-test.sh
Added timestamps to the load test results so that load can be plotted against time taken as well as numbers of PVs that exist.
> Add timestamps to load test logs

- .github/workflows/openssf_scorecard.yaml
https://github.com/nephio-project/nephio/issues/867
> Add OpenSSF scorecard gh action

- README.md
https://github.com/nephio-project/nephio/issues/867
> Add OSSF badges

- sonar-project.properties
> Skip Duplicate line check for unit-tests

- func/internal/podevaluator.go
Fixes [Issue#877](https://github.com/nephio-project/nephio/issues/877)
No longer overrides the imagePullSecret Kubernetes field in the function-runner's kpt function pods with custom registry secret but rather appends if not already there.
> fixed custom registry imagePullSecret override

- third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/internal/map.go
- third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/internal/maphelpers.go
- third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/internal/scalar.go
- third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/internal/slice.go
- third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/internal/variant.go
- third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/object_test.go
- third_party/GoogleContainerTools/kpt-functions-sdk/go/fn/resourcelist.go
Closes nephio-project/nephio#911
> Correctly parse ResultList.Results as both slice and map

- scripts/install-dev-gitea-setup.sh
Closes https://github.com/nephio-project/nephio/issues/916
> Use absolute rather than relative path in the local test gitea install script

- deployments/porch/5-rbac.yaml
- func/internal/podevaluator.go
- func/internal/podevaluator_podcachemanager_test.go
- func/internal/podevaluator_podmanager_test.go
Fix for Issue https://github.com/nephio-project/nephio/issues/879
Introduced a Service resource in front of each Function Execution Pod started by Function Runner to align the Porch deployment to Istio principles. Name of service is same as pod and follows the same lifecycle i.e. Service is created along with Pod and also deleted along with PoD after retention period.
> Added Service frontend to function evaluation pods to fix Istio integration issues

- .github/workflows/image-build-push-dev.yaml
- .github/workflows/image-build-push-release.yaml
Define a spearate gh action for building and pushing tagged/release images.
> Split dev & prod docker build-push actions
